
H_FILES = \
	main.h\

CXX_FILES =\
	main.cc \


MODULE = main

SOURCES = $(CXX_FILES) $(H_FILES)
SRCS = $(CXX_FILES)
OBJS = $(SRCS:.cc=.o)


#LDADD = -L$(prefix)/lib-$(TARGET_ARCH) -lsystemc -lm

#INCLUDES =  -I$(prefix)/include

include ./Makefile.defs
