#
# Modified style to use Makefile.defs copied from systemc tree 
# levitan@pitt.edu

H_FILES = \
	a_delay.h \
	drain.h \
	pll.h \
	top.h \

CXX_FILES =\
	a_delay.cpp \
	pll.cpp \
	top.cpp \
	main.cpp \


MODULE = main

SOURCES = $(CXX_FILES) $(H_FILES)
SRCS = $(CXX_FILES)
OBJS = $(SRCS:.cpp=.o)

include ../../Makefile.defs




